# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b27dfc5b340befc321b97c8262e88ce6b5b6161c36dbde819838e32bdfb6e6e5a8c13e2c92ca01958e2c5d70550d86eaa227ea2489db61f85d43adeae975f207

test:
  secret_key_base: 29b1651b975b13fd51f99661df58d4d804cf5ce58f9d18670d7b5ee71ff2dc3edb4e119d98fb969b170d5cad565abaf641a16a4a548d5edea7e85012696dca4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
